### ISSUE TITLE
remote name could not be resolved crash after long runtime

### ISSUE THREAD

**Issue by metal-crow** [Wulf2k/DaS-PC-MPChan#107]
Leaving DSCM running for extended periods of time (~12 hours), leads to the follow exception

```
System.Net.WebException: The remote name could not be resolved: 'chronial.de'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSCM.MainWindow.VB$StateMachine_43_updateOnlineState.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

Minor bug for most people, but annoying for Dark-Souls-PvP-AI.

**Comment by Chronial** [comment]
This is probably an issue with your internet connection. Every 10 minutes, DSCM updates the onlinestate of your recent nodes. This error is thrown if you internet connection is not working during one of these checks.

That being said, that should not cause a crash like this.

**Comment by Chronial** [comment]
Thanks for reporting.
