### ISSUE TITLE
[Test version] Doesn't launch under wine

### ISSUE THREAD

**Issue by exbb2** [Wulf2k/DaS-PC-MPChan#19]
Error message when trying to launch with .NET 4.5:

```
Unhandled Exception: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: Invalid window handle
   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name)
   at DSCM.DSCM.InitializeComponent()
   at DSCM.DSCM..ctor()
   --- End of inner exception stack trace ---
   at DSCM.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at DSCM.My.MyProject.MyForms.get_DSCM()
   at DSCM.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at DSCM.My.MyApplication.Main(String[] Args)
```

Error message when trying to launch with Wine-Mono:

```
Unhandled Exception:
System.InvalidOperationException: WinForms_SeeInnerException ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: No valid icon entry were found.
  at System.Drawing.Icon.InitFromStreamWithSize (System.IO.Stream stream, Int32 width, Int32 height) <0x1d0c8b0 + 0x00d27> in <filename unknown>:0 
  at System.Drawing.Icon..ctor (System.Runtime.Serialization.SerializationInfo info, StreamingContext context) <0x1d9a048 + 0x001bf> in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) <0x1d08ec8 + 0x00033> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) <0x1d08ec8 + ')
```

**Comment by Wulf2k** [comment]
Try this copy:
http://wulf2k.ca/pc/das/dscm-2016-05-03-23-test.rar

Not a permanent code branch in there, but just let me know if it works.

**Comment by exbb2** [comment]
@Wulf2k 
This version works. It launches correctly and I can connect to DSCM-NET and get nodes.

**Comment by Wulf2k** [comment]
The icon has been removed from the main branch.

I'll try to get a new testing version up for people to try in the next day or two.

**Comment by exbb2** [comment]
05-04-22 version crashes with same error messages. It's probably not the icon that was forcing the crash — other .Net programs with icons work fine. Maybe you have different parameters for Debug and Release builds? 

```
Unhandled Exception: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: Invalid window handle
   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name)
   at DSCM.DSCM.InitializeComponent()
   at DSCM.DSCM..ctor()
   --- End of inner exception stack trace ---
   at DSCM.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at DSCM.My.MyProject.MyForms.get_DSCM()
   at DSCM.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at DSCM.My.MyApplication.Main(String[] Args)
```

```
Unhandled Exception:
System.InvalidOperationException: WinForms_SeeInnerException ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: No valid icon entry were found.
  at System.Drawing.Icon.InitFromStreamWithSize (System.IO.Stream stream, Int32 width, Int32 height) <0x1d0bde0 + 0x00d27> in <filename unknown>:0 
  at System.Drawing.Icon..ctor (System.Runtime.Serialization.SerializationInfo info, StreamingContext context) <0x1d99cc0 + 0x001bf> in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) <0x1d08db8 + 0x00033> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) <0x1d08db8 + ')
```

**Comment by Wulf2k** [comment]
I don't expect that it's Linux in general that can't handle icons, I just think that the icon I included doesn't conform to the proper standards.  Somebody sent it in to me, I didn't create it from scratch.

I'd imagine that Linux conforms to some codified standard, whereas windows will just accept anything that looks like a picture.

I should get around to setting up a linux test environment... but hard to find the time.

**Comment by exbb2** [comment]
Wine is a Windows emulator, confirming to Linux standards would be contradictory. Regardless, the icon is actually still around in [this file](https://github.com/Wulf2k/DaS-PC-MPChan/blob/master/DaS-PC-MPChan/DSCM.resx) and is causing build errors:

```
Target GenerateResources:
		Tool /usr/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "DSCM.resx,obj/Debug/DSCM.DSCM.resources" 
/usr/lib/mono/4.5/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Invalid ResX input.
Position: Line 855, Column 5.
Inner exception: No valid icon entry were found.

	Task "GenerateResource" execution -- FAILED
	Done building target "GenerateResources" in project "/home/me/src/DaS-PC-MPChan/DaS-PC-MPChan/DSCM.vbproj".-- FAILED
```

If removing it will make it work, then who cares.

**Comment by exbb2** [comment]
@Wulf2k 

Actually the icon is the culprit. See this bug — https://bugs.winehq.org/show_bug.cgi?id=38959. Your icon is not a standard .ico file, but a new format added with Windows Vista. Apparently, no one actually used this format, so this bug is only fixed in the very latest staging version.

http://i.imgur.com/o5wjVQo.png — the icon is obviously included in 05.04 version, convert it or remove it and we're done.

**Comment by Chronial** [comment]
@exbb2 could you try whether this version works for you?
[DSCM-icontest.zip](https://github.com/Wulf2k/DaS-PC-MPChan/files/253266/DSCM-icontest.zip)

**Comment by exbb2** [comment]
@Chronial It works.

**Comment by Chronial** [comment]
Great. Thanks for testing :)
